# Generated by Django 5.2.8 on 2025-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.CharField(max_length=50)),
                ('verdict', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('ml_score', models.FloatField()),
                ('matched_rules', models.JSONField()),
            ],
        ),
    ]
